# Generated by Django 6.0.1 on 2026-01-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_companyinfo_quotation_terms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinfo",
            name="revenue",
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="account_details",
            field=models.TextField(default="n/a"),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="email",
            field=models.EmailField(default="n/a", max_length=254),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="gst_no",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.invoice"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
        ),
    ]
