# Generated by Django 6.0.1 on 2026-01-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_companyinfo_revenue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="gst_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="GST percentage (e.g. 18 for 18%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="account_details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
