# Generated by Django 6.0.1 on 2026-01-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_quotation_gst_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="business_category",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="owner_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="business_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="shopping_details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.quotation",
            ),
        ),
    ]
