# Generated by Django 6.0.1 on 2026-01-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companyinfo_address_companyinfo_business_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage (e.g. 18 for 18%)', max_digits=5),
        ),
    ]
