# Generated by Django 6.0.1 on 2026-07-26 20:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice_gst_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='account_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Image URL for company logo', max_length=500),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='signatory_title',
            field=models.CharField(blank=True, default='Authorized Signatory', max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='e.g. INV-0001', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, default='Pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat discount on subtotal', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, help_text='Custom notes / terms for client'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quote_number',
            field=models.CharField(blank=True, help_text='e.g. QTN-0001', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired'), ('Converted', 'Converted')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Quotation validity expiry date', null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Line item discount', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, default='Pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override standard price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
