# Generated by Django 6.0.1 on 2026-07-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companyinfo_account_no_companyinfo_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, help_text='Customer GSTIN', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order Number', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST + SGST (Intra-state)'), ('IGST', 'IGST (Inter-state)')], default='CGST_SGST', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order Number', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST + SGST (Intra-state)'), ('IGST', 'IGST (Inter-state)')], default='CGST_SGST', max_length=20),
        ),
    ]
