# Generated by Django 6.0.1 on 2026-07-26 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customer_gstin_invoice_po_date_invoice_po_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo photo from system', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Fallback image URL for logo', max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(default=datetime.date.today, help_text='Invoice date (defaults to today)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Quotation date (defaults to today)'),
        ),
    ]
