# Generated by Django 6.0.1 on 2026-07-26 21:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companyinfo_logo_alter_companyinfo_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload digital signature / stamp photo', null=True, upload_to='company_signatures/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='theme_color',
            field=models.CharField(choices=[('navy', 'Classic Navy Blue'), ('emerald', 'Emerald Green'), ('indigo', 'Royal Indigo'), ('charcoal', 'Corporate Charcoal')], default='navy', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN or SAC Code for GST', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI / GPay / PhonePe'), ('Bank Transfer', 'Bank Transfer (NEFT/IMPS/RTGS)'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Card', 'Credit / Debit Card')], default='UPI', max_length=30)),
                ('reference_no', models.CharField(blank=True, help_text='UTR / Transaction ID / Cheque No', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
            ],
        ),
    ]
