# Generated by Django 6.0.1 on 2026-07-26 21:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_companyinfo_signature_companyinfo_theme_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST percentage for this specific line item', max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Default GST rate for this item (e.g., 18 for 18%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST percentage for this specific line item', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fallback global GST percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fallback global GST percentage', max_digits=5),
        ),
    ]
