# Generated by Django 6.0.1 on 2026-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_invoiceitem_gst_percent_item_gst_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Sub-description / notes (e.g. Rented for 15 days, Serial #)'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Sub-description / notes (e.g. Rented for 15 days, Serial #)'),
        ),
    ]
