# Generated by Django 6.0.1 on 2026-08-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_invoiceitem_description_quotationitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Select customer for direct invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
    ]
